browser=chrome
url=https://login.salesforce.com/?locale=in

valid.username=your_email@example.com
valid.password=YourPassword123

invalid.username=invalid_user@notexist.com
invalid.password=WrongPassword999
